version: "2.1"

services:
  moodle-mariadb:
    restart: always
    environment:
      MARIADB_DATABASE: moodledb
      MARIADB_USER: moodleuser
      MARIADB_PASSWORD: c0LVADhQh55u-KO[YaOYZDk:oOINM&
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - moodle_mariadb:/var/lib/mysql
    image: mariadb:10.5

  moodle:
    restart: always
    environment:
      - DEVICE_HOSTNAME=0.0.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8442:8442"
    volumes:
      - moodle_data:/app/moodledata

volumes:
  moodle_mariadb:
  moodle_data:
